# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Favorite.destroy_all
User.destroy_all
Neighborhood.destroy_all

Favorite.reset_pk_sequence
User.reset_pk_sequence
Neighborhood.reset_pk_sequence

user_1 = User.create!(username:"nunny_r", password:"nico", avatar:"https://imgur.com/IE1BMvY", bio:"New Yorker passionate about creating a more equitable future", city:"New York", state:"New York", zipcode:10028)

neigh_1 = Neighborhood.create!(neighborhood_name: "Bushwick", image: "https://s3.amazonaws.com/nooklyn-pro/neighborhoods/1/wide/bushwick_collective_murals-11.jpg?1597087307" , about: "Bushwick has seen a lot of change over the years. In the early 1900s, it was known for its thriving distilleries and breweries. After those industries declined, it experienced a long period of blight through the 1970s and 1980s. Now the neighborhood is seeing a renaissance, as artists pushed out of Williamsburg and elsewhere move in and raise property values. Bushwick offers unconventional living spaces: The housing market is full of converted lofts in old factories, sometimes with great access to outdoor space.", flood_zone: Faker::Number.between(from:1, to: 10))
neigh_2 = Neighborhood.create!(neighborhood_name: "Park Slope", image: "https://www.nycgo.com/images/articles/9650/park-slope-01-joe-buglewicz-7499__large.jpg" ,about: "Park Slope has a tranquil, easygoing vibe and can almost feel suburban. Strollers and children of all ages are a constant presence on sidewalks, as are shoppers patronizing local boutiques and dog walkers heading up to the park. Residents are Brooklynites through and through and tend to be socially conscious, artistically minded, and committed to their community. At night, a casual restaurant scene comes alive. For anyone looking for a night out, there are plenty of beer gardens and wine bars to patronize, especially in the South Slope.", flood_zone: Faker::Number.between(from:1, to: 10))
neigh_3 = Neighborhood.create!(neighborhood_name: "East Village", image: "https://loving-newyork.com/wp-content/uploads/2018/10/Things-to-do-in-the-east-village-180927123616018.jpg",about: "Known and loved for being the birthplace of punk rock, the East Village is known for its vibrant restaurants and cocktail dens. During the day, however, the neighborhood slows down and has a tranquil feel. Meander down a leafy side street, and you'll happen upon plenty of prewar buildings and rusting fire escapes, which lend the East Village its old-fashioned charm.", flood_zone: Faker::Number.between(from:1, to: 10))
neigh_4 = Neighborhood.create!(neighborhood_name: "Astoria", image: "https://media.timeout.com/images/105293216/image.jpg",about: "Known and loved for being the birthplace of punk rock, the East Village is known for its vibrant restaurants and cocktail dens. During the day, however, the neighborhood slows down and has a tranquil feel. Meander down a leafy side street, and you'll happen upon plenty of prewar buildings and rusting fire escapes, which lend the East Village its old-fashioned charm.", flood_zone: Faker::Number.between(from:1, to: 10))
neigh_5 = Neighborhood.create!(neighborhood_name: "Elmhurst", image: "https://www.tripsavvy.com/thmb/FK63kG8rj4AX762bhhfkXqg5Ikw=/3687x2074/smart/filters:no_upscale()/Bwy_Elmhurst_Chinatown_jeh-5a47f635b39d03003717b8fc.jpg",about: "Elmhurst, Queens, is a major hub for commerce and transportation. The E, F, M, R, and 7 trains; the Long Island Rail Road; the Brooklyn-Queens Expressway; and the Long Island Expressway all run through Elmhurst, making Manhattan accessible in 20 minutes. This surfeit of commuting options also contributes to a decidedly frenetic feel, with the constant buzz amplified by Elmhurst's busy commercial scene. There are two malls here, along with countless big-box stores, groceries, medical offices, and restaurants. In fact, the wealth of eateries makes this one of the city's best neighborhoods for culinary exploration.", flood_zone: Faker::Number.between(from:1, to: 10))
neigh_6= Neighborhood.create!(neighborhood_name: "Forest Hills", image: "https://i.pinimg.com/originals/74/63/4d/74634d785212e546693f35b1598fa60c.jpg",about: "Bisected by Queens Boulevard, Forest Hills offers two types of city living: Urban apartment complexes on one side and the other, the storied Forest Hills Gardens. Whichever side of the boulevard you live on, this suburban neighborhood is teeming with lots of public outdoor space and also schools that out-perform those in the city.", flood_zone: Faker::Number.between(from:1, to: 10))
neigh_7= Neighborhood.create!(neighborhood_name: "Harlem", image: "https://imgs.6sqft.com/wp-content/uploads/2018/05/29142332/Central-Harlem-Historic-District.png",about: "Harlem begins directly above Central Park, where you will find busy thoroughfares adjacent to quiet tree-lined blocks lined with brownstones and pre-war apartment buildings.", flood_zone: Faker::Number.between(from:1, to: 10))
neigh_8= Neighborhood.create!(neighborhood_name: "Sunset Park", image: "https://cdn.theculturetrip.com/wp-content/uploads/2019/04/shutterstock_1352970851-1.jpg",about: "Tucked between Park Slope and Bay Ridge, Sunset Park is a bit of a hike from Manhattan and Downtown Brooklyn. Relative obscurity has kept rents low for decades, although that appears to be slowly changing as brownstone families are priced out of Park Slope and Carroll Gardens. A new wave is beginning here: Industry City, a cluster of 16 warehouses on cobblestone streets, now hosts Smorgasburg, The Brooklyn Flea, and Mister Sunday, a day dance party in the summer. The galleries, tech conferences, rooftop movie screenings, and countless artisan shops in that complex are slowly putting Sunset Park on the map for young people.", flood_zone: Faker::Number.between(from:1, to: 10))
neigh_9= Neighborhood.create!(neighborhood_name: "Washington Heights", image: "https://nypost.com/wp-content/uploads/sites/2/2018/06/washington-heights-new-hipster-haven.jpg?quality=80&strip=all",about: "Washington Heights is so far uptown that it feels a little removed from the action, which translates into affordable rents and large apartments in predominately prewar buildings. Popular with young professionals and students, the neighborhood is vibrant, thriving, and decidedly down-to-earth. Expansive parks make it a popular place for dog owners. At its core, the neighborhood has always been diverse; throw into the mix plenty of Columbia Med School students in scrubs and off-duty cops, and that will round out the scene at many a happy hour in the Heights.", flood_zone: Faker::Number.between(from:1, to: 10))
neigh_10= Neighborhood.create!(neighborhood_name: "Greenpoint", image: "https://www.brickunderground.com/sites/default/files/blog/images/GreenpointPrimage.jpeg",about: "A former industrial and maritime neighborhood, Greenpoint was once primarily home to Polish and Irish immigrants and is now home to a large artist's community. The nightlife, restaurant and music scene have burgeoned in recent years as energy and activity in Williamsburg creeps north towards Greenpoint. As a result, the neighborhood’s low-key, tucked-away vibe may not last for long, although poor access to public transportation may deter some new residents. Despite all the recent change, Greenpoint still hangs onto its rich history and an old-school community.", flood_zone: Faker::Number.between(from:1, to: 10))
neigh_11= Neighborhood.create!(neighborhood_name: "Gowanus", image: "https://static01.nyt.com/images/2017/10/07/nyregion/00gowanus1/00gowanus1-superJumbo.jpg",about: "Looking out from the F train as it rises above ground, you get a bird's-eye view of Gowanus. From this vantage point, you can see the canal clearly cutting through the heart of the neighborhood and spreading out from it are lots teeming with scrap metal, concrete mixing plants, and lumberyards. The polluted canal became a Superfund site for long-term clean up in 2009, and the area surrounding the waterway was rezoned for residential development.", flood_zone: Faker::Number.between(from:1, to: 10))

fave_1 = Favorite.create!(title: neigh_1.neighborhood_name, image:neigh_1.image, about: neigh_1.about, user_id:user_1.id, neighborhood_id:neigh_1.id )
fave_2 = Favorite.create!(title: neigh_2.neighborhood_name, image: neigh_2.image, about: neigh_2.about, user_id: user_1.id, neighborhood_id:neigh_2.id)


puts("🌈🌈🌈")